
title: Shooters Wichita # your title
url: 'http://shooterswichita.com'
baseurl: '/shooters' #change it according to your repository name



# Profile information
yourname: Shooters Wichita  ## put your name
location: Wichita, KS


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
## twitter: http://www.twitter.com  ## your twitter account url
## linkedin: http://www.linkedin.com  ## your linkedin account url
## dribbble: http://www.dribble.com  ## you dribbble account url
## foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
